# Generated by Django 3.1.6 on 2021-02-07 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Usuario')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('peso', models.FloatField(help_text='Peso del Deportista', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('estatura', models.FloatField(help_text='Estatura del Deportista', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('entrenador', models.CharField(help_text='Entrenador del Deportista', max_length=128)),
                ('imagen', models.URLField(help_text='URL Foto de Perfil', verbose_name='Foto')),
            ],
            options={
                'verbose_name_plural': 'Deportistas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRegistrado',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Usuario')),
                ('email', models.EmailField(help_text='Correo electrónico del Usuario', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Usuarios Registrados',
            },
        ),
    ]
